apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lightdash.fullname" . }}
  labels:
    {{- include "lightdash.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lightdash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lightdash.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "lightdash.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.image.command }}
          args: {{ .Values.image.args }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ include "lightdash.database.secret.passwordKey" .}}
                  name: {{ include "lightdash.postgresql.secretName" . }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: {{ include "lightdash.database.secret.userKey" . }}
                  name: {{ include "lightdash.postgresql.secretName" . }}
          envFrom:
          {{- if $.Values.configMap }}
            - configMapRef:
                name: {{ template "lightdash.fullname" $ }}
          {{- end }}
          {{- if $.Values.secrets }}
            - secretRef:
                name: {{ template "lightdash.fullname" $ }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 5
            httpGet:
              path: /api/v1/livez
              port: {{ .Values.service.port }}
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /api/v1/health
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.extraContainers }}
          {{- toYaml .Values.extraContainers | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
